language: node_js
node_js:
  - "12.14.1"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project taller-de-ajedrez-12741 --token $FIREBASE_TOKEN
