language: node_js
node_js:
  - "8"
script:
 - echo "Deploy!!"
angular:
 - npm install -g @angular/cli
build:
  - ng build --prod=true
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project taller-de-ajedrez-12741 --token $FIREBASE_TOKEN